# -*- coding: utf-8 -*-
"""assgn2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15SY_KJe4UD8EGv8GKQGNjp0WuI0wxruK
"""

import pandas as pd

data = pd.read_csv("https://raw.githubusercontent.com/Insiya24/datasets/main/WA_Fn-UseC_-HR-Employee-Attrition.csv")

data.axes

data

data.head()

data.tail()

data.dtypes

data_EF= data.groupby(["PerformanceRating"])[["StandardHours"]]

data.isnull().sum()

data['PercentSalaryHike'].mean()

data['PercentSalaryHike'].fillna(15.2206,inplace=True)

data['EmployeeCount'].mean()

data['EmployeeCount'].fillna(1.0,inplace=True)

data['EmployeeNumber'].mean()

data['EmployeeNumber'].fillna(1026.0517,inplace=True)

data['EnvironmentSatisfaction'].mean()

data['EnvironmentSatisfaction'].fillna(2.7229,inplace=True)

data['HourlyRate'].mean()

data['HourlyRate'].fillna(65.8820,inplace=True)

data['JobLevel'].mean()

data['JobLevel'].fillna(2.0611,inplace=True)

data['JobInvolvement'].mean()

data['JobInvolvement'].fillna(2.7329,inplace=True)

data['JobSatisfaction'].mean()

data['JobSatisfaction'].fillna(2.7265,inplace=True)

data.isna().sum()

data['Gender'].mode()

data['Gender'].fillna('Male',inplace=True)

data['EducationField'].mode()

data['EducationField'].fillna('Life Sciences',inplace=True)

data['Department'].mode()

data['Department'].fillna('Research & Development',inplace=True)

from sklearn import preprocessing
le = preprocessing.LabelEncoder()

data["Gender"]=le.fit_transform(data["Gender"])

data['EducationField']=le.fit_transform(data['EducationField'])

data["Department"]=le.fit_transform(data["Gender"])

data["Attrition"]=le.fit_transform(data["Attrition"])

data['MaritalStatus']=le.fit_transform(data['MaritalStatus'])

data['OverTime']=le.fit_transform(data['OverTime'])

import seaborn
import matplotlib.pyplot as pt
pt.figure(figsize=(14,14))
correlation = data.corr ()
heatmap = seaborn.heatmap(correlation, annot = True)
pt.show()